import book1 from "../images/book1.jpg";
import book2 from "../images/book2.jpg";
import book3 from "../images/book3.webp";
const ProductList = [
  {
    id: 1,
    title: "Calculus Edition 2",
    isbn: "978-0-691-14836-6",
    ownerId: "f89930a2-f9ba-4622-8e07-dcc0d42d460f",
    courseId: "6b4db8a5-18d1-429d-9614-4d88c95ab485",
    price: 45,
    imageLink: book1,
    isSold: false,
  },
  {
    id: 2,
    title: "Calculus Edition 2",
    isbn: "978-0-691-14836-6",
    ownerId: "f89930a2-f9ba-4622-8e07-dcc0d42d460f",
    courseId: "6b4db8a5-18d1-429d-9614-4d88c95ab485",
    price: 45,
    imageLink: book2,
    isSold: false,
  },
  {
    id: 3,
    title: "Programming in C",
    isbn: "978-0-691-14836-6",
    ownerId: "f89930a2-f9ba-4622-8e07-dcc0d42d460f",
    courseId: "6b4db8a5-18d1-429d-9614-4d88c95ab485",
    price: 45,
    imageLink: book3,
    isSold: false,
  },
  // {
  //   id: 4,
  //   title: "Calculus Edition 2",
  //   author: "James Stewart",
  //   description: "Its for Math 233 taght by Professor Brown",
  //   price: 45,
  //   thumb: book1,
  // },
  // {
  //   id: 5,
  //   title: "Calculus Edition 2",
  //   author: "James Stewart",
  //   description: "Its for Math 233 taght by Professor Brown",
  //   price: 45,
  //   thumb: book1,
  // },
  // {
  //   id: 6,
  //   title: "Calculus Edition 2",
  //   author: "James Stewart",
  //   description: "Its for Math 233 taght by Professor Brown",
  //   price: 45,
  //   thumb: book1,
  // },
  // {
  //   id: 7,
  //   title: "Calculus Edition 2",
  //   author: "James Stewart",
  //   description: "Its for Math 233 taght by Professor Brown",
  //   price: 45,
  //   thumb: book1,
  // },
  // {
  //   id: 8,
  //   title: "Calculus Edition 2",
  //   author: "James Stewart",
  //   description: "Its for Math 233 taght by Professor Brown",
  //   price: 45,
  //   thumb: book1,
  // },
  // {
  //   id: 9,
  //   title: "Calculus Edition 2",
  //   author: "James Stewart",
  //   description: "Its for Math 233 taght by Professor Brown",
  //   price: 45,
  //   thumb: book1,
  // },
  // {
  //   id: 10,
  //   title: "Calculus Edition 2",
  //   author: "James Stewart",
  //   description: "Its for Math 233 taght by Professor Brown",
  //   price: 45,
  //   thumb: book1,
  // },
  // {
  //   id: 11,
  //   title: "Calculus Edition 2",
  //   author: "James Stewart",
  //   description: "Its for Math 233 taght by Professor Brown",
  //   price: 45,
  //   thumb: book1,
  // },
];

export default ProductList;
