# Uncomment the next line to define a global platform for your project
platform :ios, '13.4.1'

target 'MovieSearch' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieSearch
pod 'youtube-ios-player-helper'
pod "YoutubePlayer-in-WKWebView", "~> 0.3.0"
 
end
