components:
    schemas:
        Book:
            type: object
            properties:
                title:
                    title: Book.title
                    type: string
                isbn:
                    title: Book.isbn
                    type: string
                ownerId:
                    title: Book.ownerId
                    type: string
                courseId:
                    title: Book.courseId
                    type: string
                dateCreated:
                    title: Book.dateCreated
                    type: string
                dateUpdated:
                    title: Book.dateUpdated
                    type: string
                price:
                    title: Book.price
                    type: number
                    format: float
                imageLink:
                    title: Book.imageLink
                    type: string
                sold:
                    title: Book.sold
                    type: boolean