components:
    schemas:
        AuthenticatedUser:
            type: object
            properties:
                id:
                    title: AuthenticatedUser.id
                    type: string
                username:
                    title: AuthenticatedUser.username
                    type: string
                firstName:
                    title: AuthenticatedUser.firstName
                    type: string
                lastName:
                    title: AuthenticatedUser.lastName
                    type: string
                token:
                    title: AuthenticatedUser.token
                    type: string