components:
    schemas:
        User:
            title: User
            type: object
            properties:
                id:
                    title: User.id
                    type: string
                username:
                    title: User.username
                    type: string
                password:
                    title: User.password
                    type: string
                firstName:
                    title: User.firstName
                    type: string
                lastName: 
                    title: User.lastName
                    type: string
                phoneNum:
                    title: User.phoneNum
                    type: string
                dateCreated:
                    title: User.dateCreated
                    type: string
                dateUpdated:
                    title: User.dateUpdated
                    type: string